"""empty message

Revision ID: 058b86736184
Revises: c2793a312889
Create Date: 2016-10-14 16:43:37.115398

"""

# revision identifiers, used by Alembic.
revision = '058b86736184'
down_revision = 'c2793a312889'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'tag-post_post_id_fkey', 'tag-post', type_='foreignkey')
    op.create_foreign_key(None, 'tag-post', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag-post', type_='foreignkey')
    op.create_foreign_key(u'tag-post_post_id_fkey', 'tag-post', 'posts', ['post_id'], ['id'])
    ### end Alembic commands ###
