"""empty message

Revision ID: 407d7c66bf91
Revises: 3f826b17078c
Create Date: 2016-09-11 16:13:56.640412

"""

# revision identifiers, used by Alembic.
revision = '407d7c66bf91'
down_revision = '3f826b17078c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
