"""empty message

Revision ID: 9c6dbb30c95c
Revises: None
Create Date: 2016-10-07 19:37:22.140937

"""

# revision identifiers, used by Alembic.
revision = '9c6dbb30c95c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'title')
    ### end Alembic commands ###
